### ISSUE TITLE
GitHub Collaborathon - Nov 3, 2022

### ISSUE THREAD

**Issue by ctb** [datalab-affiliates/events#1]
Details below; I will post updates to this issue, so if you're interested & logged into GitHub, you can either subscribe to this issue (see lower right), OR just check in on this issue for details.

Thursday Nov 3, from ~2-5pm, looks good for the most people! We’ll do it in hybrid format so if you’re remote you’re welcome!

Let’s plan to start at 2pm (so, really, 2:15pm ;). I’ll set up a zoom room and post the info here (and send it to the people on the when2meet), and be in the Shields 360 room. And then I’ll stick around until people lose interest or need to run out to other things. I’ll try to recruit some more github users, too.

The goal will be to get you “onto” github and using it for a few small things, and then figuring out what you might actually want to use it for. I’ll put together a short list of potential topics and then we can work 1:1 or in small groups.

See you then!

Oh, and please feel free to invite people that you think might be interested! We should have room for more! Just tell them to contact me (ctbrown@ucdavis.edu) and I’ll make sure they’re “in” on any additional information. (Or you can forward info to them)

## possible topics

Thinking out loud about topics -

- creating a free github account, if you don’t have one!
- creating a new private (or public) repository; inviting collaborators
- making your first commit via Web edit, then upload
- cloning repo & making your first commit via git
- making more commits
- setting up branches and pull requests
- brainstorming use cases for git in your life

**Comment by ctb** [comment]
ooh, I should talk about git stash, too.

**Comment by sarahheuck** [comment]
I'll be there! The course I'm TAing goes until 2 so I might be like 10 minutes late, but I'm excited to learn

**Comment by squisquater** [comment]
I'll also be there.

**Comment by agrupenhoff** [comment]
I have to leave at 3 pm but excited to stop by!

**Comment by ctb** [comment]
The Shields 360 classroom is busy until 3pm today with a class, so we'll meet in DataLab Conference Room-Shields 362!

**Comment by ctb** [comment]
hi all  - join zoom.us/mytitusbrown/ for zoomtasticness!

**Comment by ctb** [comment]
we are in the back datalab room! come in and walk all the way back

**Comment by ctb** [comment]
done!
