### ISSUE TITLE
SQLite hands-on: Thursday 3:30pm, Jan 19th, 2023.

### ISSUE THREAD

**Issue by ctb** [datalab-affiliates/events#2]
## A Hands-On Introduction to SQL with SQLite!

SQLite is the amazing little embedded database that could! It comes with Python, it’s on every Apple device ever made, and it just … plain … works. Really, really well.

You might be interested in this session (generally) and SQLite (specifically) if any or all of the following apply -

* you have too much spreadsheet/dataframe-like data to fit easily in memory;
* you’ve heard about SQL but never really used it;
* you want to access the same data from multiple programming languages (like Python and R);
* you are naturally curious;

Join me on Thursday (Jan 19th) at 3:30pm to go through a little SQL and SQLite tutorial!

In this session I’ll develop a simple database for storing information about a personal book collection, and we’ll explore it together. I’ll show -

* how to design a simple SQL schema
* how to add data into the database with Python, and how to retrieve it
* how to explore database contents from the command line

No particular background is needed to follow along other than a tolerance for minor technical difficulties ;).

I’ll provide some installation instructions before the workshop, on the github issue for this event (see below).

---

Please watch this space for location & zoom connection information - you can subscribe to this issue to get updates about just this workshop, if you like.

Or, contact ctbrown@ucdavis.edu and hope I see your e-mail in time to respond 😅

**Comment by ctb** [comment]
(Hoping to do this in Shields 360 / DataLab space, but need to hear back from Glenda first ;))

**Comment by sarahheuck** [comment]
Unfortunately this is during my lab meeting so I won't be able to make it, but I would love to learn more about sql at some point.

**Comment by ctb** [comment]
We'll meet in Shields 360! Zoom link to follow.

I'll make notes and recordings available ;).

For Windows users who want to try things out locally:
* go to https://www.sqlite.org/download.html
* find "Precompiled Binaries for Windows"
* download and install [sqlite-tools-win32-x86-3400100.zip](https://www.sqlite.org/2022/sqlite-tools-win32-x86-3400100.zip)


For Mac OS X and Linux computers, sqlite3 _should_ come installed with Python.

I'll provide a binder Web site as well, so no worries if install fails or you don't get to it!

**Comment by ctb** [comment]
Zoom link:  https://ucdavis.zoom.us/j/96263572921?pwd=eEtNZmEwV2svZnlha1V6MVZRTzV4UT09

**Comment by ctb** [comment]
Binder link:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ngs-docs/2023-ggg298-sourmash-compare/stable?urlpath=rstudio)

This will create an RStudio Server running in the cloud.

To get to a command line, go to Terminal...

To run sqlite3, run `sqlite3 database.sql` at the terminal!

**Comment by ctb** [comment]
Here's some starting notes.

https://hackmd.io/2wcEylvPSDCw-wa0sk0tdQ?view

**Comment by PLNReynolds** [comment]
For a SQL tutorial, we have a workshop reader here: https://ucdavisdatalab.github.io/workshop_intro_to_sql/

You can contribute, submit issues, etc. for that workshop here: https://github.com/ucdavisdatalab/workshop_intro_to_sql

**Comment by PLNReynolds** [comment]
Related aside - For designing schemas, we like using [Lucid Chart ](https://www.lucidchart.com/pages/landing?utm_source=google&utm_medium=cpc&utm_campaign=_chart_en_us_mixed_search_brand_exact_&km_CPC_CampaignId=1457964857&km_CPC_AdGroupID=57044764032&km_CPC_Keyword=lucidchart&km_CPC_MatchType=e&km_CPC_ExtensionID=&km_CPC_Network=g&km_CPC_AdPosition=&km_CPC_Creative=442433231228&km_CPC_TargetID=kwd-33511936169&km_CPC_Country=9032521&km_CPC_Device=c&km_CPC_placement=&km_CPC_target=&gclid=Cj0KCQiA8aOeBhCWARIsANRFrQGE713AjDys7CZb24LgM_yNHwiHK59WqVQPU2VsI-mo9XwA2jmRNL0aAtcBEALw_wcB)(the free version is typically fine). We use it for visualizing and planning our workflows, and then it will translate to SQL for setting up the database.

**Comment by ctb** [comment]
video posted here: https://video.ucdavis.edu/media/t/1_y2wyfifl
